### ISSUE TITLE
Collaborating on a Linked GTFS spec

### ISSUE THREAD

**Issue by pietercolpaert** [kasei/gtfs-rdf#1]
Hi @kasei,

Your initiative was just brought to my attention. However, I noticed the URIs defined in this repository do not dereference anymore (I get a "Forbidden" at e.g., http://myrdf.us/gtfs/vocab/agency) and there haven't been any updates since 2010. GTFS has updated a lot since then.

Next to this repository, also @iand introduced the transit vocabulary, with a very similar goal, in 2011. In 2015, Ian has deprecated his vocabulary in favor of a vocabulary maintained by @abyrd and myself, as part of Open Knowledge International's Open Transport working group: https://github.com/iand/vocab-transit/issues/4. We now aim to maintain this vocabulary further at this location: https://github.com/opentransport/linked-gtfs.

Would you be willing to adapt the URIs in your vocabulary to Linked-GTFS?

**Comment by kasei** [comment]
Hey @pietercolpaert. Obviously I haven't touched this code in a while. If it's simply a matter of changing URLs, I'd be happy to do that (or, even better, get a PR). Otherwise, happy to add a README that points people at more up-to-date code/projects like yours.

**Comment by pietercolpaert** [comment]
Alright, thanks! Will do a PR!

**Comment by kasei** [comment]
I'm going to archive this repo and so will close this issue. Please feel free to fork if you'd like to do anything with it in the future.
